apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-12T23:33:49Z"
  generateName: sample-workspace-
  labels:
    app.kubernetes.io/component: workspace
    app.kubernetes.io/instance: sample
    app.kubernetes.io/managed-by: pulumi-kubernetes-operator
    app.kubernetes.io/name: pulumi
    apps.kubernetes.io/pod-index: "0"
    controller-revision-hash: sample-workspace-847579fbf
    statefulset.kubernetes.io/pod-name: sample-workspace-0
  name: sample-workspace-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: sample-workspace
    uid: 9ce975e4-5bd2-4168-81ed-d34ade744272
  resourceVersion: "202746"
  uid: c65b8f47-8ed8-4766-b307-8fb737efcfc9
spec:
  containers:
  - env:
    - name: PULUMI_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          key: accessToken
          name: pulumi-api-secret
    image: pulumi/pulumi-kubernetes-agent:latest
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 50051
      name: grpc
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4v87k
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: sample-workspace-0
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: sample-workspace
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: tmp
  - name: kube-api-access-4v87k
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T23:33:50Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T23:33:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T23:33:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T23:33:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T23:33:49Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b9dd4bc7d59efb0ca7428e1a0bbc1581d62134d0541576a860653dc001c4a1c5
    image: pulumi/pulumi-kubernetes-agent:latest
    imageID: docker://sha256:3c6563c49d34d039e04668356c180d2344277515e39bcf24bc3e41444228f4ab
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-07-12T23:33:49Z"
  hostIP: 192.168.65.3
  hostIPs:
  - ip: 192.168.65.3
  phase: Running
  podIP: 10.1.28.101
  podIPs:
  - ip: 10.1.28.101
  qosClass: BestEffort
  startTime: "2024-07-12T23:33:49Z"
