apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-12T18:13:53Z"
  generateName: sample-workspace-
  annotations:
    pulumi.com/initialized: "true"
  labels:
    app.kubernetes.io/component: workspace
    app.kubernetes.io/instance: sample
    app.kubernetes.io/managed-by: pulumi-kubernetes-operator
    app.kubernetes.io/name: pulumi
    apps.kubernetes.io/pod-index: "0"
    controller-revision-hash: sample-workspace-847579fbf
    statefulset.kubernetes.io/pod-name: sample-workspace-0
  name: sample-workspace-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: sample-workspace
    uid: 609fe9df-5da2-410d-a2cf-7a974d2a47bf
  resourceVersion: "159524"
  uid: 4f7042f4-07e6-4d93-8364-636b6dd726db
spec:
  containers:
  - env:
    - name: PULUMI_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          key: accessToken
          name: pulumi-api-secret
    image: pulumi/pulumi-kubernetes-agent:latest
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 50051
      name: grpc
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rkllb
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: sample-workspace-0
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: sample-workspace
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: tmp
  - name: kube-api-access-rkllb
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T18:13:54Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T18:13:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T18:13:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T18:13:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-07-12T18:13:53Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f1cf5a365809d2b6b8da0adab7c5441bbd12d372dd17f369800cb94b926729d0
    image: pulumi/pulumi-kubernetes-agent:latest
    imageID: docker://sha256:1bdbbd79e6c98b472def22577728ba6f83df812ae6829f017bbaf4725129cccc
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-07-12T18:13:53Z"
  hostIP: 192.168.65.3
  hostIPs:
  - ip: 192.168.65.3
  phase: Running
  podIP: 10.1.28.94
  podIPs:
  - ip: 10.1.28.94
  qosClass: BestEffort
  startTime: "2024-07-12T18:13:53Z"
